export const baseIcons = {
  'student': 'graduation-cap',
  'dashboard': 'dashboard',
  'trophy': 'trophy',
  'privacy': 'key',
  'alarm outline': 'bell-o',
  'lab': 'flask',
  'bug': 'bug',
  'code': 'code',
  'sitemap': 'sitemap',
  'protect': 'shield',
  'unhide': 'eye',
  'random': 'random',
  'retweet': 'retweet',
  'sign language': 'sign-language',
  'bomb': 'bomb',
  'sun': 'sun-o',
  'law': 'balance-scale',
  'life ring': 'life-ring',
  'anchor': 'anchor',
  'hand scissors': 'hand-scissors-o',
  'snowflake outline': 'snowflake-o',
  'thermometer empty': 'thermometer-empty',
  'tv': 'tv',
  'cube': 'cube',
  'asterisk': 'asterisk',
  'database': 'database',
  'plane': 'plane',
  'shipping': 'truck',
  'umbrella': 'umbrella',
  'fire': 'fire',
  'cocktail': 'glass',
  'book': 'book',
  'gift': 'gift',
  'road': 'road',
  'rocket': 'rocket',
  'bar': 'beer',
  'legal': 'legal',
  'area chart': 'area-chart',
  'line chart': 'line-chart',
  'camera retro': 'camera-retro',
  'bath': 'bath',
  'hourglass empty': 'hourglass-half',
  'find': 'binoculars',
  'options': 'sliders',
  'ticket': 'ticket',
  'copyright': 'copyright',
  'heartbeat': 'heartbeat',
  'at': 'at',
  'eyedropper': 'eyedropper',
  'trademark': 'trademark',
  'hourglass half': 'hourglass-half',
  'alarm mute': 'bell-slach',
  'history': 'history',
  'percent': 'percent',
  'hashtag': 'hashtag',
  'shopping basket': 'shopping-basket',
  'shopping bag': 'shopping-bag',
  'file excel outline': 'file-excel-o',
  'barcode': 'barcode',
  'html5': 'html5',
  'fork': 'code-fork',
  'empty star': 'star-o',
  'heart': 'heart',
  'smile': 'smile-o',
  'frown': 'frown-o',
  'star half empty': 'star-half-empty'
};